// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_to_the_dungeons_and_beyond = "CgkIxsGD340MEAIQCg"; // <GPGSID>
        public const string leaderboard_high_score = "CgkIxsGD340MEAIQAQ"; // <GPGSID>
        public const string achievement_space_cow_abunga_dude = "CgkIxsGD340MEAIQBw"; // <GPGSID>
        public const string achievement_an_apple_a_day = "CgkIxsGD340MEAIQAw"; // <GPGSID>
        public const string achievement_eat_your_greens = "CgkIxsGD340MEAIQBA"; // <GPGSID>
        public const string achievement_stabby_pointy_things = "CgkIxsGD340MEAIQCA"; // <GPGSID>
        public const string achievement_youre_so_special = "CgkIxsGD340MEAIQBQ"; // <GPGSID>
        public const string leaderboard_bubble_addict__total_bubbles = "CgkIxsGD340MEAIQDA"; // <GPGSID>
        public const string achievement_sign_me_up = "CgkIxsGD340MEAIQCQ"; // <GPGSID>
        public const string leaderboard_sharp_shooter__highest_accuracy = "CgkIxsGD340MEAIQCw"; // <GPGSID>
        public const string achievement_its_a_cow_jim_but_not_as_we_know_it = "CgkIxsGD340MEAIQBg"; // <GPGSID>

}

